from tkinter import *
from tkinter.messagebox import *
from tkcalendar import DateEntry
import datetime as dt
import sqlite3
root=Tk()
root.title("booking")
root.geometry("1000x1000")
con = sqlite3.Connection("my_datbase")
cur = con.cursor()
img=PhotoImage(file = "starbus.png")
Label(root, image = img).pack()
Label(root,text='Online Bus Booking System',fg='red',bg="light blue",font='Calibri 30').pack()
Label(root, text="Check Booked Ticket",font="times 15 bold").pack()
Label(root,text="Enter The Mobile Number",font="times 15 bold",fg="green").place(x=500,y=365)
c=Entry(root)
c.place(x=750,y=370)
def check_seat():

    cur.execute(f"select name from ticket where mobile_no ={c.get()} order by rowid desc LIMIT 1")
    Label(root,text="Passenger",font="times 15 bold",fg="green").place(x=470,y=400)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=570,y=400)
    cur.execute(f"select gender from ticket where mobile_no ={c.get()} order by rowid desc LIMIT 1")
    Label(root,text="Gender",font="times 15 bold",fg="green").place(x=740,y=400)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=820,y=400)
    cur.execute(f"select seats from ticket where mobile_no ={c.get()}  order by rowid desc LIMIT 1")
    Label(root,text="No. Of Seats",font="times 15 bold",fg="green").place(x=470,y=450)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=590,y=450)
    cur.execute(f"select mobile_no from ticket where mobile_no ={c.get()}  order by rowid desc LIMIT 1")
    Label(root,text="Phone no.",font="times 15 bold",fg="green").place(x=740,y=450)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=840,y=450)
    cur.execute(f"select age from ticket where mobile_no ={c.get()}  order  by rowid desc LIMIT 1")
    Label(root,text="Age",font="times 15 bold",fg="green").place(x=470,y=500)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=590,y=500)
    cur.execute(f"select gender from ticket where mobile_no ={c.get()}  order by rowid desc LIMIT 1")
    Label(root,text="Bus Detail",font="times 15 bold",fg="green").place(x=740,y=500)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=850,y=500)
    cur.execute(f"select travel_date from ticket where mobile_no ={c.get()}  order by rowid desc LIMIT 1")
    Label(root,text="Travel On",font="times 15 bold",fg="green").place(x=470,y=550)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=570,y=550)
    cur.execute(f"select travel_date from ticket where mobile_no ={c.get()}  order by rowid desc LIMIT 1")
    Label(root,text="Booked On",font="times 15 bold",fg="green").place(x=740,y=550)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=850,y=550)
    cur.execute(f"select boarding_point from ticket where mobile_no ={c.get()}  order by rowid desc LIMIT 1")
    Label(root,text="From",font="times 15 bold",fg="green").place(x=470,y=600)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=570,y=600)
    cur.execute(f"select final_point from ticket where mobile_no ={c.get()}  order by rowid desc LIMIT 1")
    Label(root,text="To",font="times 15 bold",fg="green").place(x=740,y=600)
    Label(root,text=cur.fetchall(),font="times 15 bold").place(x=850,y=600)
Button(root,text="Show",command=check_seat,bg="green",relief='raised',font='times 10 ').place(x=900,y=370)
Button(root,text="HOME",bg="green",font='times 10').place(x=950,y=370)
root.mainloop()