from tkinter import *
from tkinter.messagebox import *
import sqlite3
con = sqlite3.Connection("my_datbase")
cur = con.cursor()
root=Tk()
root.title("booking")
root.geometry("1000x1000")
img=PhotoImage(file = "starbus.png")
Label(root, image = img).pack()
Label(root,text='Online Bus Booking System',fg='red',bg="light blue",font='Calibri 30').pack()
Label(root,text='Add Operator Details',fg='green',font='Calibri 20').pack()
def add():
    showinfo("BUS ENTRY","OPERATOR ENTRY ADDED")
    cur.execute("create table if not exists emp(operator_id int,name varchar(20) ,address varchar(30),phone int,email varchar(30),primary key(operator_id))")
    cur.execute("insert into emp values (?,?,?,?,?)",(int(e11.get()),str(e12.get()),str(e13.get()),int(e14.get()),str(e15.get()))) 
    con.commit()
def show():
    Label(root,text="ALL BUS DETAILS",bg="red",fg="green",font='Calibri 15').place(x=650,y=450)
    cur.execute("select * from emp")
    Label(root,text=cur.fetchall(),font='times 11 bold').place(x=00,y=500)
Label(root,text='Operator ID',font='times 11 bold').place(x=50,y=400)
e11=Entry(root)
e11.place(x=140,y=400)
Label(root,text='Name',font='times 11 bold').place(x=280,y=400)
e12=Entry(root)
e12.place(x=330,y=400)
Label(root,text='Address',font='times 11 bold').place(x=460,y=400)
e13=Entry(root)
e13.place(x=530,y=400)
Label(root,text='Phone',font='times 11 bold').place(x=660,y=400)
e14=Entry(root)
e14.place(x=710,y=400)
Label(root,text='Email',font='times 11 bold').place(x=840,y=400)
e15=Entry(root)
e15.place(x=890,y=400)
def add2():
        cur.execute(f"delete from emp where operator_id={e11.get()}")
        con.commit()
        cur.execute('insert into emp values(?,?,?,?,?)',(int(e11.get()),str(e12.get()),str(e13.get()),int(e14.get()),str(e15.get())))
        con.commit()
Button(root,text="EDIT",command=add2,bg="green",font='times 10').place(x=1090,y=400)
Button(root,text="ADD",command=add,bg="green",font='times 10').place(x=1040,y=400)
Button(root,text="SHOW",command=show,bg="green",font='times 10').place(x=1140,y=400)
Button(root,text="HOME",bg="green",font='times 10').place(x=1200,y=400)
root.mainloop()