from tkinter import *
from tkinter.messagebox import *
import sqlite3
con = sqlite3.Connection("my_datbase")
cur = con.cursor()
root=Tk()
root.title("booking")
root.geometry("1000x1000")
img=PhotoImage(file = "starbus.png")
Label(root, image = img).pack()
Label(root,text='Online Bus Booking System',fg='red',bg="light blue",font='Calibri 30').pack()
Label(root,text='Add Bus Details',fg='green',font='Calibri 20').pack()
def add():
    showinfo("BUS ENTRY","BUS ENTRY ADDED")
    cur.execute("create table if not exists bus(bus_id int,bus_type varchar(20) ,capacity int,fare int,operaror_id int,route_id int,primary key(bus_id))")
    cur.execute("insert into bus values (?,?,?,?,?,?)",(int(e11.get()),str(e12.get()),int(e13.get()),int(e14.get()),int(e15.get()),int(e16.get()))) 
    con.commit()
def show():
    Label(root,text="ALL BUS DETAILS",bg="red",fg="green",font='times 11 bold').place(x=650,y=600)
    cur.execute("select * from bus")
    Label(root,text=cur.fetchall(),font='Calibri 10').place(x=00,y=650)
Label(root,text='Bus Id',font='times 11 bold').place(x=80,y=400)
e11=Entry(root)
e11.place(x=135,y=400)
Label(root,text='Bus Type',font='times 11 bold').place(x=270,y=400)
e12=Entry(root)
e12.place(x=340,y=400)
Label(root,text='Capacity',font='times 11 bold').place(x=470,y=400)
e13=Entry(root)
e13.place(x=535,y=400)
Label(root,text='Fare RS.',font='times 11 bold').place(x=660,y=400)
e14=Entry(root)
e14.place(x=720,y=400)
Label(root,text='Operator ID',font='times 11 bold').place(x=825,y=400)
e15=Entry(root)
e15.place(x=920,y=400)
Label(root,text='Route ID',font='times 11 bold').place(x=1005,y=400)
e16=Entry(root)
e16.place(x=1075,y=400)
def add2():
        cur.execute(f"delete from bus where bus_id={e11.get()}")
        con.commit()
        cur.execute('insert into bus values(?,?,?,?,?,?)',(int(e11.get()),str(e12.get()),int(e13.get()),int(e14.get()),int(e15.get()),int(e16.get())))
        con.commit()
Button(root,text="EDIT",command=add2,bg="green",font='times 12').place(x=600,y=500)
Button(root,text="ADD",command=add,bg="green",font='times 12').place(x=530,y=500)
Button(root,text="SHOW",command=show,bg="green",font='times 12').place(x=670,y=500)
Button(root,text="HOME",bg="green",font='times 12').place(x=750,y=500)
root.mainloop()