from tkinter import *
from tkinter.messagebox import *
import sqlite3
con = sqlite3.Connection("my_datbase")
cur = con.cursor()
root=Tk()
root.title("booking")
root.geometry("1000x1000")
img=PhotoImage(file = "starbus.png")
Label(root, image = img).pack()
Label(root,text='Online Bus Booking System',fg='red',bg="light blue",font='Calibri 30').pack()
Label(root,text='Add Bus Running Details',fg='green',font='Calibri 20').pack()
def add():
    showinfo("BUS ENTRY","BUS RUNNING DETAIL ADDED")
    cur.execute("create table if not exists run (bus_id int,running_date date ,seat_available int,foreign key(bus_id) references bus(bus_id))")
    cur.execute("insert into run values (?,?,?)",(int(e11.get()),str(e12.get()),int(e13.get()))) 
    con.commit()
def show():
    Label(root,text="ALL BUS RUNNING DETAILS",bg="red",fg="green",font='Calibri 15').place(x=650,y=450)
    cur.execute("select * from run")
    Label(root,text=cur.fetchall(),font='times 12 bold').place(x=00,y=500)
Label(root,text='Bus Id ',font='times 12 bold').place(x=220,y=400)
e11=Entry(root)
e11.place(x=270,y=400)
Label(root,text='Running date',font='times 12 bold').place(x=420,y=400)
e12=Entry(root)
e12.place(x=520,y=400)
Label(root,text='Seat available',font='times 12 bold').place(x=660,y=400)
e13=Entry(root)
e13.place(x=760,y=400)
def add2():
        cur.execute(f"delete from run where bus_id={e11.get()}")
        con.commit()
        cur.execute('insert into run values(?,?,?)',(int(e11.get()),str(e12.get()),int(e13.get())))
        con.commit()
Button(root,text="EDIT",command=add2,bg="green",font='times 10').place(x=960,y=400)
Button(root,text="ADD",command=add,bg="green",font='times 10').place(x=900,y=400)
Button(root,text="SHOW",command=show,bg="green",font='times 10').place(x=1020,y=400)
Button(root,text="HOME",bg="green",font='times 10').place(x=1080,y=400)
root.mainloop()