from tkinter import *
from tkinter.messagebox import *
import sqlite3
con = sqlite3.Connection("add_bus")
cur = con.cursor()
root=Tk()
root.title("booking")
root.geometry("1000x1000")
img=PhotoImage(file = "starbus.png")
Label(root, image = img).pack()
Label(root,text='Online Bus Booking System',fg='red',bg="light blue",font='Calibri 30').pack()
Label(root,text='Add Bus Details',fg='green',font='Calibri 20').pack()
v1=StringVar()
Label(root,text='Bus Id ').place(x=100,y=400)
e1=Entry(root)
e1.place(x=140,y=400)
Label(root,text='Bus Type').place(x=290,y=400)
e2=Entry(root)
e2.place(x=350,y=400)
Label(root,text='Capacity').place(x=470,y=400)
e3=Entry(root)
e3.place(x=530,y=400)
Label(root,text='Fare RS.').place(x=650,y=400)
e4=Entry(root)
e4.place(x=700,y=400)
Label(root,text='Operator ID').place(x=800,y=400)
e5=Entry(root)
e5.place(x=880,y=400)
Label(root,text='Route ID').place(x=950,y=400)
e50=Entry(root)
e50.place(x=1000,y=400)
def add():
    showinfo("BUS ENTRY","BUS ENTRY ADDED")
    cur.execute("create table if not exists bus(bus_id int,bus_type varchar(20) ,capacity int,fare int,operaror_id int,route_id int,primary key(bus_id))")
    cur.execute('insert into bus values(?,?,?,?,?,?)',(int(e1.get()),str(e2.get()),int(e3.get()),int(e4.get()),int(e5.get()),int(e50.get())))
    con.commit()
def show():
    Label(root,text="ALL BUS DETAILS",bg="red",fg="green").place(x=650,y=600)
    cur.execute("select * from bus")
    Label(root,text=cur.fetchall()).place(x=00,y=650)
Label(root,text='Bus Id ').place(x=100,y=500)
e11=Entry(root)
e11.place(x=140,y=500)
Label(root,text='Bus Type').place(x=290,y=500)
e12=Entry(root)
e12.place(x=350,y=500)
Label(root,text='Capacity').place(x=470,y=500)
e13=Entry(root)
e13.place(x=530,y=500)
Label(root,text='Fare RS.').place(x=650,y=500)
e14=Entry(root)
e14.place(x=700,y=500)
Label(root,text='Operator ID').place(x=800,y=500)
e15=Entry(root)
e15.place(x=880,y=500)
Label(root,text='Route ID').place(x=950,y=500)
e16=Entry(root)
e16.place(x=1000,y=500)
def add2():
        showinfo("BUS ENTRY","BUS ENTRY ADDED")
        cur.execute("update bus set bus_type =(?) ,capacity=(?) ,fare=(?),operaror_id=(?),route_id=(?) where bus_id= (?)",(str(e12.get()),int(e13.get()),int(e14.get()),int(e15.get()),int(e16.get()),int(e11.get())))
Button(root,text="EDIT",command=add2,bg="green",font='times 10').place(x=1140,y=500)
Button(root,text="ADD",command=add,bg="green",font='times 10').place(x=1140,y=400)
Button(root,text="SHOW",command=show,bg="green",font='times 10').place(x=1210,y=450)
Button(root,text="HOME",bg="green",font='times 10').place(x=1260,y=450)
root.mainloop()