from tkinter import *
from tkinter.messagebox import *
from tkcalendar import DateEntry
import datetime as dt
import sqlite3
root=Tk()
root.title("booking")
root.geometry("1000x1000")
con = sqlite3.Connection("my_datbase")
cur = con.cursor()
img=PhotoImage(file = "starbus.png")
Label(root, image = img).pack()
Label(root,text='Online Bus Booking System',fg='red',bg="light blue",font='Calibri 30').pack()
Label(root, text="BUS TICKET",font="times 15 bold").pack()
cur.execute("select name from ticket order by rowid desc LIMIT 1")
Label(root,text="Passenger",font="times 15 bold",fg="green").place(x=470,y=400)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=570,y=400)
cur.execute("select gender from ticket order by rowid desc LIMIT 1")
Label(root,text="Gender",font="times 15 bold",fg="green").place(x=740,y=400)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=820,y=400)
cur.execute("select seats from ticket order by rowid desc LIMIT 1")
Label(root,text="No. Of Seats",font="times 15 bold",fg="green").place(x=470,y=450)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=590,y=450)
cur.execute("select mobile_no from ticket order by rowid desc LIMIT 1")
Label(root,text="Phone no.",font="times 15 bold",fg="green").place(x=740,y=450)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=840,y=450)
cur.execute("select age from ticket order by rowid desc LIMIT 1")
Label(root,text="Age",font="times 15 bold",fg="green").place(x=470,y=500)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=590,y=500)
cur.execute("select gender from ticket order by rowid desc LIMIT 1")
Label(root,text="Bus Detail",font="times 15 bold",fg="green").place(x=740,y=500)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=850,y=500)
cur.execute("select travel_date from ticket order by rowid desc LIMIT 1")
Label(root,text="Travel On",font="times 15 bold",fg="green").place(x=470,y=550)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=570,y=550)
cur.execute("select travel_date from ticket order by rowid desc LIMIT 1")
Label(root,text="Booked On",font="times 15 bold",fg="green").place(x=740,y=550)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=850,y=550)
cur.execute("select boarding_point from ticket order by rowid desc LIMIT 1")
Label(root,text="From",font="times 15 bold",fg="green").place(x=470,y=600)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=570,y=600)
cur.execute("select final_point from ticket order by rowid desc LIMIT 1")
Label(root,text="To",font="times 15 bold",fg="green").place(x=740,y=600)
Label(root,text=cur.fetchall(),font="times 15 bold").place(x=850,y=600)
root.mainloop()